include "./sketchlib/list.skh";

// List<int> empty_list;

List<int> empty_list(){
	return empty();
}

generator int intgen(List<int> a, int bnd){
    if (bnd == 0){return ??;}
	if(??){
        return {|??| ?? + intgen(a, bnd-1)|};
    }
    if(??){
        return ((Cons<int>)a).val;
    }
    return mylen(listgen(a)) + intgen(a,bnd-1);
}



generator List<int> listgen(List<int> a){
    if(??){
        return empty();
    }
    return ((Cons<int>)a).next;
}

int mylen(List<int> a) {
	// List<int> empty_list = empty();
	if(a == empty_list()) {
		return intgen(a,2);
	}else {
		// return intgen(a);
        // return ?? + mylen(((Cons<int>)a).next);
        return intgen(a,2);
	}
}

harness void main() {
	// empty_list = empty();
	List<int> a = empty();
	List<int> b = add(add(add(a,3), 4), 5);
	List<int> c = add(add(add(add(a,3), 4), 5), 6);
	// List<int> d = add(add(add(add(add(add(a,3), 4), 5), 6), 7), 8);
	assert mylen(a) == 0;
	assert mylen(b) == 3;
	assert mylen(c) == 4;
	// assert mylen(d) == 6;
}
